// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5u_q1deMBN2kQSSNgOfGvRdgq-RG-cwQ',
    appId: '1:690656580069:web:0c4b27dbac394a7cca9f0c',
    messagingSenderId: '690656580069',
    projectId: 'spotify1510',
    authDomain: 'spotify1510.firebaseapp.com',
    storageBucket: 'spotify1510.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS2w7F21_TBpGb_dcYQZTLya65sxQzICY',
    appId: '1:690656580069:android:32452375eeba927cca9f0c',
    messagingSenderId: '690656580069',
    projectId: 'spotify1510',
    storageBucket: 'spotify1510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlAct7RAKiZbd5iT8d-E-dIZhGpCxD1GY',
    appId: '1:690656580069:ios:7d7dfd7b11adb92cca9f0c',
    messagingSenderId: '690656580069',
    projectId: 'spotify1510',
    storageBucket: 'spotify1510.appspot.com',
    iosBundleId: 'com.example.spotify',
  );
}
